name: Tutorials

on:
  workflow_dispatch:
  push:
    branches: [master, test-me-*]
  pull_request:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['Ubuntu', 'Windows', 'MacOS']
        python-version: ['3.7', '3.10']
        pytorch-version: ['1.13.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly -c pytorch
        make setup

    - name: Check deps
      shell: bash -l {0}
      run: make check-deps

    - name: Generate tutorials
      shell: bash -l {0}
      run: make generate

    - name: Run tutorials
      shell: bash -l {0}
      run: make execute

  build:
    needs: test
    name: Build tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ['Ubuntu']
        python-version: ['3.10']
        pytorch-version: ['1.13.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch=${{ matrix.pytorch-version }} cpuonly -c pytorch
        make setup

    - name: Check deps
      shell: bash -l {0}
      run: make check-deps

    - name: Build tutorials pages
      shell: bash -l {0}
      run: make generate
