name: Tutorials

on:
  workflow_dispatch:
  push:
    branches: [master, test-me-*]
  pull_request:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        kornia-ref: ['main'] # TODO: coverage check through multiple versions: , 'v0.7.1', 'v0.7.0']

    uses: kornia/workflows/.github/workflows/tutorials.yml@v1.4.0
    with:
      ref: ${{ matrix.kornia-ref }}

  build:
    needs: test
    name: Build tutorials
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ['ubuntu']
        kornia-ref: ['main']

    steps:
    - uses: kornia/workflows/.github/actions/env@v1.4.0
      with:
        ref: ${{ matrix.kornia-ref }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt  --upgrade
        pip install -r requirements-dev.txt  --upgrade

    - uses: quarto-dev/quarto-actions/setup@v2

    - name: Check deps
      shell: bash -l {0}
      run: make check-deps

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html
        path: .
